package dev.darl.sagip.chat

import java.util.Locale

/**
 * Requests that need a phone number, not an explanation. Answered deterministically (no model):
 * faster, and a number must never be generated by an LLM.
 */
sealed interface QuickIntent {
    /** "ano ang number ng bumbero" — look up contacts of these kinds near the user. */
    data class FindContacts(val kinds: Set<String>) : QuickIntent

    /** "call my mom" / "tawagan si asawa" — dial the emergency contact the user saved. */
    data object CallFamily : QuickIntent
}

object QuickIntents {
    private val CALL_WORDS = Regex("\\b(call|dial|tawag|tawagan|tumawag|tatawag|contact|text)\\b")
    private val NUMBER_WORDS = Regex("\\b(number|numero|hotline|phone|telepono|cp|contact|tawag|tawagan|call|dial)\\b")

    private val FAMILY = Regex(
        "\\b(mom|mommy|mother|mama|mamá|nanay|inay|ina|dad|daddy|father|papa|tatay|itay|ama|wife|husband|asawa|misis|mister|" +
            "partner|girlfriend|boyfriend|anak|son|daughter|kapatid|brother|sister|ate|kuya|lola|lolo|family|pamilya|" +
            "emergency contact|kamag-anak|kaibigan|friend)\\b"
    )

    private val KINDS: List<Pair<Regex, Set<String>>> = listOf(
        Regex("\\b(bumbero|bombero|bfp|fire (station|dept|department|truck)|firefighter|sunog)\\b") to setOf("fire", "emergency"),
        Regex("\\b(pulis|police|pnp|barangay tanod|tanod)\\b") to setOf("police", "tanod", "emergency"),
        Regex("\\b(ospital|hospital|clinic|er|emergency room|doktor|doctor)\\b") to setOf("hospital", "ambulance", "emergency"),
        Regex("\\b(ambulansya|ambulance|rescue|saklolo)\\b") to setOf("ambulance", "emergency", "hospital"),
        Regex("\\b(red cross|redcross|pula)\\b") to setOf("redcross"),
        Regex("\\b(drrmo|cdrrmo|mdrrmo|disaster)\\b") to setOf("drrmo", "emergency"),
        Regex("\\b(barangay|brgy|health center|bhw)\\b") to setOf("barangay_hall", "health", "tanod"),
        Regex("\\b(911|emergency|hotline|saklolo)\\b") to setOf("emergency", "redcross"),
    )

    fun detect(raw: String): QuickIntent? {
        val t = raw.lowercase(Locale.ROOT)
        if (CALL_WORDS.containsMatchIn(t) && FAMILY.containsMatchIn(t) && !KINDS.any { it.first.containsMatchIn(t) && !t.contains("emergency contact") }) {
            return QuickIntent.CallFamily
        }
        if (NUMBER_WORDS.containsMatchIn(t)) {
            val kinds = KINDS.filter { it.first.containsMatchIn(t) }.flatMap { it.second }.toSet()
            if (kinds.isNotEmpty()) return QuickIntent.FindContacts(kinds)
            if (Regex("\\b(emergency|hotline|911)\\b").containsMatchIn(t)) return QuickIntent.FindContacts(setOf("emergency", "redcross"))
        }
        return null
    }
}
