"""Regenerate docs/IMAGE-MANIFEST.md from the packs + current illustration files.
Run from repo root:  python3 docs/gen_image_manifest.py
Conventions mirror app/.../data/Illustrations.kt (keep in sync)."""
import json, glob, os, collections
A = 'app/src/main/assets'
EXT = ('png', 'webp', 'jpg', 'jpeg')
topics = collections.OrderedDict()
for f in sorted(glob.glob(f'{A}/packs/*.json')):
    for c in json.load(open(f)):
        if c['lang'] == 'en':
            topics[(c['pack'], c['topic'])] = (c['title'], c['severity'], len([l for l in c['text'].split('\n') if l.strip()]))
tdir = f'{A}/illustrations/topics'
files = set(os.listdir(tdir)) if os.path.isdir(tdir) else set()
root = set(os.listdir(f'{A}/illustrations')) if os.path.isdir(f'{A}/illustrations') else set()
has = lambda base: any(f'{base}.{e}' in root for e in EXT)
hasT = lambda base: any(f'{base}.{e}' in files for e in EXT)
packs = sorted({p for p, _ in topics})
o = ['# SAGIP — Image manifest', '', 'Auto-generated by `docs/gen_image_manifest.py`.', '',
     '## Where files go (under `app/src/main/assets/illustrations/`)', '',
     '| Slot | Path | Used for | Size hint |', '|---|---|---|---|',
     '| Category cover | `<category>.png` (category = pack id) | Home card + category header | 1200×900 |',
     '| Topic hero | `topics/<topic>.hero.png` | topic card + detail header | 1200×900 |',
     '| Step image | `topics/<topic>.step<N>.png` | under step N on the detail screen | 1200×800 |',
     '| Reference image | `topics/<topic>.<anything>.png` | "Reference images" row | 1200×900 |', '',
     'png / webp / jpg are picked up automatically; a missing file shows a placeholder slot.', '',
     '## Category covers', '', '| Category | File | Status |', '|---|---|---|']
o += [f"| {p} | `{p}.png` | {'✅' if has(p) else '⬜ missing'} |" for p in packs]
o += ['', '## Topics', '', '| Pack | Topic | Title | Severity | Steps | Hero | Extra images |', '|---|---|---|---|---|---|---|']
miss = 0
for (p, t), (title, sev, n) in topics.items():
    h = hasT(f'{t}.hero'); miss += 0 if h else 1
    ex = sorted(f for f in files if f.startswith(t + '.') and not f.startswith(t + '.hero.'))
    o.append(f"| {p} | `{t}` | {title} | {sev} | {n} | {'✅' if h else '⬜'} | {', '.join(ex) if ex else '—'} |")
o += ['', f'**{len(topics)} topics · {len(topics)-miss} heroes done · {miss} missing.**']
open('docs/IMAGE-MANIFEST.md', 'w').write('\n'.join(o))
print(len(topics), 'topics', miss, 'heroes missing')
